### PR TITLE
Python Language Tutorial Files Added

### PR DESCRIPTION
**Pull request by GunvantGMC**
**Python Tutorials Added**

1) Python Tutorial Files Added
2) What is programming tutorial added
3) Python installation tutorial added
4) Getting started tutorial added
5) Variables in Python tutorial added
6) List & Tuples tutorial added
7) Required image assets added
8) Minor code updation

### CODE REVIEW

**Comment by GunvantGMC** [comment]
@shubhamAW  Kindly check out

**Comment by shubhamAW** [comment]
Thanks @GunvantGMC for such valuable contribution

**Comment by GunvantGMC** [comment]
**Thanks**

**Comment by shubhamAW** [comment]
image
It run fine in local but prod some links are broken

**Comment by GunvantGMC** [comment]
I think file name is not updated 
image

make following changes in MD **"Installing-Python.md"**

**Comment by shubhamAW** [comment]
change are live now 😊

**Comment by GunvantGMC** [comment]
🙌👍

**Pull request merged**
